// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-verse-of-the-day.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { VERSE_OF_DAY } from "npm:@/data/scriptures";
var get_verse_of_the_day_default = defineTool({
  name: "get_verse_of_the_day",
  title: "Get verse of the day",
  description: "Get today's featured Hindu scripture verse from the FAITH app, including Sanskrit, transliteration, English translation, and commentary.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(VERSE_OF_DAY, null, 2) }],
    structuredContent: { verse: VERSE_OF_DAY }
  })
});

// src/lib/mcp/tools/list-scriptures.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { SCRIPTURES } from "npm:@/data/scriptures";
var list_scriptures_default = defineTool2({
  name: "list_scriptures",
  title: "List scriptures",
  description: "List all Hindu scripture books available in the FAITH library (Bhagavad Gita, Upanishads, Vedas, Puranas, Yoga Sutras, Hanuman Chalisa, etc.) with each book's passage titles and references.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const summary = SCRIPTURES.map((b) => ({
      id: b.id,
      title: b.title,
      subtitle: b.subtitle,
      passageCount: b.passages.length,
      passages: b.passages.map((p) => ({ id: p.id, title: p.title, reference: p.reference }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { books: summary }
    };
  }
});

// src/lib/mcp/tools/get-passage.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
import { findPassage } from "npm:@/data/scriptures";
var get_passage_default = defineTool3({
  name: "get_passage",
  title: "Get scripture passage",
  description: "Get the full text of a Hindu scripture passage by id (e.g. `gita-2-47`, `isha-1`). Returns Sanskrit, transliteration, translation, and commentary when available. Use `list_scriptures` first to discover valid ids.",
  inputSchema: { id: z.string().describe("Passage id, for example `gita-2-47`.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const passage = findPassage(id);
    if (!passage) {
      return { content: [{ type: "text", text: `No passage found for id \`${id}\`.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(passage, null, 2) }],
      structuredContent: { passage }
    };
  }
});

// src/lib/mcp/tools/list-observances.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { OBSERVANCES, PANCHANG } from "npm:@/data/practice";
var list_observances_default = defineTool4({
  name: "list_upcoming_observances",
  title: "List upcoming observances",
  description: "List upcoming Hindu festivals and vratas (observances) with dates and descriptions, plus today's Panchang (tithi, nakshatra).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ panchang: PANCHANG, observances: OBSERVANCES }, null, 2) }],
    structuredContent: { panchang: PANCHANG, observances: OBSERVANCES }
  })
});

// src/lib/mcp/tools/list-mandirs.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { MANDIRS } from "npm:@/data/hindu";
var list_mandirs_default = defineTool5({
  name: "list_mandirs",
  title: "List UK mandirs",
  description: "List Hindu mandirs (temples) across the UK that are featured in the FAITH app. Optionally filter by a city substring (e.g. `London`, `Leicester`).",
  inputSchema: { city: z2.string().optional().describe("Optional city substring to filter mandirs.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ city }) => {
    const q = city?.trim().toLowerCase();
    const results = q ? MANDIRS.filter((m) => m.city.toLowerCase().includes(q)) : MANDIRS;
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { mandirs: results }
    };
  }
});

// src/lib/mcp/tools/list-events.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { EVENTS, EVENT_TYPES } from "npm:@/data/community";
var list_events_default = defineTool6({
  name: "list_community_events",
  title: "List community events",
  description: "List UK Hindu community events in the FAITH app (mandir aartis, NHSF socials, festivals, seva, study circles). Optionally filter by city substring or event type.",
  inputSchema: {
    city: z3.string().optional().describe("Optional city substring filter."),
    type: z3.enum(EVENT_TYPES).optional().describe("Optional event type filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ city, type }) => {
    const q = city?.trim().toLowerCase();
    const results = EVENTS.filter((e) => (q ? e.city.toLowerCase().includes(q) : true) && (type ? e.type === type : true));
    const trimmed = results.map((e) => ({
      id: e.id,
      title: e.title,
      type: e.type,
      host: e.host,
      city: e.city,
      date: e.date,
      distanceKm: e.distanceKm,
      description: e.description
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(trimmed, null, 2) }],
      structuredContent: { events: trimmed }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
import { PRODUCTS, CATEGORIES, VENDORS } from "npm:@/data/marketplace";
var list_products_default = defineTool7({
  name: "list_products",
  title: "List marketplace products",
  description: "List Puja and Hindu lifestyle products from UK vendors in the FAITH marketplace. Optionally filter by category (e.g. `Puja Thalis`, `Murtis`, `Incense & Oils`, `Sweets & Prasad`).",
  inputSchema: {
    category: z4.enum(CATEGORIES).optional().describe("Optional product category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const filtered = category ? PRODUCTS.filter((p) => p.category === category) : PRODUCTS;
    const withVendor = filtered.map((p) => ({
      ...p,
      vendor: VENDORS.find((v) => v.id === p.vendorId)?.name
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(withVendor, null, 2) }],
      structuredContent: { products: withVendor }
    };
  }
});

// src/lib/mcp/tools/list-audio.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
import { TRACKS, AUDIO_CATEGORIES } from "npm:@/data/audio";
var list_audio_default = defineTool8({
  name: "list_audio_tracks",
  title: "List audio tracks",
  description: "List ad-free devotional audio tracks (slokas, bhajans, meditation mantras, aartis) available in the FAITH Listen tab. Optionally filter by category.",
  inputSchema: {
    category: z5.enum(AUDIO_CATEGORIES).optional().describe("Optional audio category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const results = category ? TRACKS.filter((t) => t.category === category) : TRACKS;
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { tracks: results }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "faith-mcp",
  title: "FAITH \u2014 UK Hindu Hub",
  version: "0.1.0",
  instructions: "Tools for the FAITH app, a UK Hindu community hub. Use these tools to read the Verse of the Day, browse the scripture library (Bhagavad Gita, Upanishads, Vedas, Puranas, Yoga Sutras, etc.) and fetch full passages, discover upcoming Hindu observances and today's Panchang, find UK mandirs and NHSF community events, browse the Puja marketplace, and list devotional audio tracks. All data is public.",
  tools: [
    get_verse_of_the_day_default,
    list_scriptures_default,
    get_passage_default,
    list_observances_default,
    list_mandirs_default,
    list_events_default,
    list_products_default,
    list_audio_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
